# Generated by Django 4.1 on 2022-10-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='comment',
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'fantasy'), ('literary', 'literary'), ('mystery', 'mystery'), ('non-fiction', 'non-fiction'), ('science-fiction', 'science-fiction'), ('thriller', 'thriller')], default='', max_length=120),
        ),
    ]
